# Generated by Django 4.1.4 on 2022-12-15 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(default=20)),
                ('address', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('slottime', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=20)),
                ('balance', models.IntegerField(default=1000)),
                ('mobile', models.IntegerField(default=111)),
            ],
            options={
                'db_table': 'PaymentMaster',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('image', models.ImageField(default='abc,jpg', upload_to='Images')),
                ('section', models.CharField(max_length=20)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category')),
            ],
            options={
                'db_table': 'Pets',
            },
        ),
        migrations.CreateModel(
            name='Pet_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('price', models.FloatField(default=1000)),
                ('front', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('side', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('description', models.CharField(max_length=200)),
                ('lifespan', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.pets')),
            ],
            options={
                'db_table': 'Pet_Cat',
            },
        ),
        migrations.CreateModel(
            name='Old_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1000)),
                ('dateoforder', models.DateTimeField(default=datetime.datetime(2022, 12, 16, 1, 10, 5, 623444))),
                ('details', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo')),
            ],
            options={
                'db_table': 'Old_Order',
            },
        ),
    ]
