# Generated by Django 4.1.4 on 2022-12-15 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_old_order_dateoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_order',
            name='dateoforder',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 1, 25, 15, 124688)),
        ),
    ]
